name: gh-pages

on: [push]

jobs:
  build:
    if: ${{ contains( github.event.head_commit.message,'pages') }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@3951f0dfe7a07e2313ec93c75700083e2005cbab # v4.3.0
        with:
          dotnet-version: '9.0'
      - name: restore workload
        run: dotnet workload restore
      - name: Publish with dotnet
        run: dotnet publish superHost.h5/superHost.h5.csproj -p:CompressionEnabled=false  -c Release  --output build 
      - name: Setup Pages
        uses: actions/configure-pages@983d7736d9b0ae728b81ab479565c72886d7745b # v5.0.0

      - name: 上传生成物
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: build

      - name: 部署到 Github Pages
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5